"""Shared data schemas used across agents, schedulers, workers, and profilers."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from typing import Any, Self


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat()


@dataclass(slots=True)
class SerializableSchema:
    """Small JSON helper for dataclass-based schemas."""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, sort_keys=True)


@dataclass(slots=True)
class ToolCall(SerializableSchema):
    """A structured tool invocation generated by an agent."""

    tool_call_id: str
    agent_id: str
    tool_type: str
    input_uri: str
    input_size_mb: float
    page_count: int = 0
    image_count: int = 0
    deadline_sec: float | None = None
    priority: int = 0
    created_at: str = field(default_factory=_utc_now_iso)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))


@dataclass(slots=True)
class WorkerInfo(SerializableSchema):
    """Static information about a worker."""

    worker_id: str
    supported_tools: list[str]
    max_concurrency: int = 1
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))


@dataclass(slots=True)
class WorkerState(SerializableSchema):
    """Dynamic runtime state reported by a worker."""

    worker_id: str
    supported_tools: list[str]
    queue_len: int = 0
    cpu_util: float = 0.0
    memory_util: float = 0.0
    network_latency_ms: float = 0.0
    is_online: bool = True
    updated_at: str = field(default_factory=_utc_now_iso)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))


@dataclass(slots=True)
class ScheduleDecision(SerializableSchema):
    """The scheduler's decision for one tool call."""

    tool_call_id: str
    selected_worker: str
    policy_name: str
    score: float | None = None
    reason: str | None = None
    decided_at: str = field(default_factory=_utc_now_iso)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))


@dataclass(slots=True)
class ToolResult(SerializableSchema):
    """Execution result returned by a worker."""

    tool_call_id: str
    worker_id: str
    success: bool
    output_uri: str | None = None
    execution_time_sec: float = 0.0
    error_message: str | None = None
    finished_at: str = field(default_factory=_utc_now_iso)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))


@dataclass(slots=True)
class TraceRecord(SerializableSchema):
    """Profiler record for a completed tool call."""

    tool_call_id: str
    agent_id: str
    tool_type: str
    selected_worker: str
    policy_name: str
    queue_wait_time_sec: float
    execution_time_sec: float
    total_latency_sec: float
    success: bool
    timeout: bool
    reward: float
    input_transfer_time_sec: float = 0.0
    output_transfer_time_sec: float = 0.0
    error_message: str | None = None
    recorded_at: str = field(default_factory=_utc_now_iso)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        return cls(**data)

    @classmethod
    def from_json(cls, data: str) -> Self:
        return cls.from_dict(json.loads(data))
